# Fix template to use labels correctly to be a valid k8s resourece
#
# Use toJson, toYaml and indent+trim functions
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa
  labels:
    {{ $.Values.labels | toYaml | indent 4 | trim }}
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: myhpa
  targetCPUUtilizationPercentage: 85
