# Use `range` to define these hpas from the .Values.hpas array
{{ range .Values.hpas -}}
---
{{ $name:= .name -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ $name }}
  targetCPUUtilizationPercentage: 85
{{ end -}}

