# Extract the service name into a variable.
#
# +1: Extract subexpressions to variables
{{ $title := .Values.title -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ trimAll "-" (lower (regexReplaceAll "[^a-zA-Z-]" (regexReplaceAll " " $title "-") "")) }}
  annotations:
    service-title: "{{ $title }}"
spec:
  clusterIP: 10.2.2.61
  externalTrafficPolicy: Cluster
  ports:
  - name: "svc"
    port: 9051
  selector:
    app: {{ trimAll "-" (lower (regexReplaceAll "[^a-zA-Z-]" (regexReplaceAll " " $title "-") "")) }}
  type: NodePort
